// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjeKUYY_RSyKVeSMBu3i8PjuF9CJoNHrU',
    appId: '1:605394812728:web:13199827cf16f5bfc20bcd',
    messagingSenderId: '605394812728',
    projectId: 'church-app-59ce4',
    authDomain: 'church-app-59ce4.firebaseapp.com',
    storageBucket: 'church-app-59ce4.firebasestorage.app',
    measurementId: 'G-5RNV659VL6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8jN2-RjOnxl-9Rc7gdM3OHAP2L9ArRo0',
    appId: '1:605394812728:android:535247c74508bb30c20bcd',
    messagingSenderId: '605394812728',
    projectId: 'church-app-59ce4',
    storageBucket: 'church-app-59ce4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOU8ZhO6ryn-bspj0OxfoqdsslXG5GDes',
    appId: '1:605394812728:ios:57958315aa5d93b4c20bcd',
    messagingSenderId: '605394812728',
    projectId: 'church-app-59ce4',
    storageBucket: 'church-app-59ce4.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOU8ZhO6ryn-bspj0OxfoqdsslXG5GDes',
    appId: '1:605394812728:ios:57958315aa5d93b4c20bcd',
    messagingSenderId: '605394812728',
    projectId: 'church-app-59ce4',
    storageBucket: 'church-app-59ce4.firebasestorage.app',
    iosBundleId: 'com.example.churchApp',
  );
}
